<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
  xmlns:xhtml="http://www.w3.org/1999/xhtml">
  <xsl:output method="html" encoding="UTF-8" indent="yes"/>

  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>TelePlus Care — XML Sitemap</title>
        <style>
          *{box-sizing:border-box;margin:0;padding:0}
          body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:#fafafa;color:#222;line-height:1.5}
          .header{background:linear-gradient(135deg,#621C72 0%,#8B3A9F 100%);color:#fff;padding:36px 24px 28px}
          .header-inner{max-width:1100px;margin:0 auto}
          .brand{font-size:22px;font-weight:700;letter-spacing:.3px;margin-bottom:6px}
          .title{font-size:30px;font-weight:700;margin-bottom:8px}
          .subtitle{font-size:15px;opacity:.9}
          .stats{margin-top:18px;display:flex;flex-wrap:wrap;gap:12px}
          .stat{background:rgba(255,255,255,.15);padding:8px 14px;border-radius:100px;font-size:13px;font-weight:500}
          .container{max-width:1100px;margin:24px auto;padding:0 24px 60px}
          .meta{background:#fff;border:1px solid #eee;border-radius:12px;padding:14px 18px;margin-bottom:18px;font-size:13px;color:#666}
          .meta strong{color:#222}
          table{width:100%;border-collapse:collapse;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.04);border:1px solid #eee}
          thead{background:#f5f0f7}
          th{text-align:left;padding:14px 16px;font-size:12px;font-weight:600;color:#621C72;text-transform:uppercase;letter-spacing:.6px;border-bottom:1px solid #eadcf0}
          td{padding:14px 16px;font-size:14px;border-bottom:1px solid #f3f3f3;vertical-align:middle}
          tr:last-child td{border-bottom:0}
          tr:hover td{background:#fcf8fd}
          a{color:#621C72;text-decoration:none;font-weight:500;word-break:break-all}
          a:hover{text-decoration:underline}
          .pri{display:inline-block;background:#621C72;color:#fff;padding:2px 10px;border-radius:100px;font-size:12px;font-weight:600}
          .pri.med{background:#8B3A9F}
          .pri.low{background:#a87bb8}
          .freq{color:#666;font-size:13px;text-transform:capitalize}
          .imgs{color:#888;font-size:12px}
          .imgs strong{color:#621C72}
          .footer{text-align:center;color:#999;font-size:12px;margin-top:24px;padding-top:18px;border-top:1px solid #eee}
          .footer a{color:#621C72}
          @media (max-width:640px){
            .title{font-size:22px}
            th,td{padding:10px 8px;font-size:13px}
            th:nth-child(3),td:nth-child(3),th:nth-child(4),td:nth-child(4){display:none}
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="header-inner">
            <div class="brand">TelePlus Care</div>
            <h1 class="title">XML Sitemap</h1>
            <p class="subtitle">Virtual healthcare across Canada — Alberta, Ontario, BC &amp; Saskatchewan</p>
            <div class="stats">
              <xsl:if test="s:sitemapindex">
                <span class="stat">
                  <xsl:value-of select="count(s:sitemapindex/s:sitemap)"/> child sitemaps
                </span>
              </xsl:if>
              <xsl:if test="s:urlset">
                <span class="stat">
                  <xsl:value-of select="count(s:urlset/s:url)"/> URLs
                </span>
                <span class="stat">
                  <xsl:value-of select="count(s:urlset/s:url/image:image)"/> images indexed
                </span>
              </xsl:if>
            </div>
          </div>
        </div>

        <div class="container">
          <div class="meta">
            <strong>About this sitemap:</strong> This XML file is for search engines (Google, Bing, Perplexity, ChatGPT). It tells crawlers which pages exist on telepluscare.com, when they were last updated, and how often they change. Humans can ignore this — visit
            <a href="https://telepluscare.com/" style="color:#621C72;font-weight:600">telepluscare.com</a> instead.
          </div>

          <xsl:apply-templates select="s:sitemapindex"/>
          <xsl:apply-templates select="s:urlset"/>

          <p class="footer">
            Generated by TelePlus Care · Compliant with <a href="https://www.sitemaps.org/protocol.html">sitemaps.org/0.9</a>
          </p>
        </div>
      </body>
    </html>
  </xsl:template>

  <!-- Sitemap index (master) -->
  <xsl:template match="s:sitemapindex">
    <table>
      <thead>
        <tr>
          <th>Sitemap</th>
          <th>Last Modified</th>
        </tr>
      </thead>
      <tbody>
        <xsl:for-each select="s:sitemap">
          <xsl:sort select="s:loc"/>
          <tr>
            <td><a href="{s:loc}"><xsl:value-of select="s:loc"/></a></td>
            <td><xsl:value-of select="s:lastmod"/></td>
          </tr>
        </xsl:for-each>
      </tbody>
    </table>
  </xsl:template>

  <!-- URL set (child sitemap) -->
  <xsl:template match="s:urlset">
    <table>
      <thead>
        <tr>
          <th>URL</th>
          <th>Priority</th>
          <th>Change Freq</th>
          <th>Last Modified</th>
          <th>Images</th>
        </tr>
      </thead>
      <tbody>
        <xsl:for-each select="s:url">
          <xsl:sort select="s:priority" data-type="number" order="descending"/>
          <xsl:sort select="s:loc"/>
          <tr>
            <td><a href="{s:loc}"><xsl:value-of select="s:loc"/></a></td>
            <td>
              <xsl:variable name="p" select="s:priority"/>
              <xsl:choose>
                <xsl:when test="$p &gt;= 0.9"><span class="pri"><xsl:value-of select="$p"/></span></xsl:when>
                <xsl:when test="$p &gt;= 0.7"><span class="pri med"><xsl:value-of select="$p"/></span></xsl:when>
                <xsl:otherwise><span class="pri low"><xsl:value-of select="$p"/></span></xsl:otherwise>
              </xsl:choose>
            </td>
            <td class="freq"><xsl:value-of select="s:changefreq"/></td>
            <td><xsl:value-of select="s:lastmod"/></td>
            <td class="imgs">
              <xsl:choose>
                <xsl:when test="count(image:image) &gt; 0"><strong><xsl:value-of select="count(image:image)"/></strong></xsl:when>
                <xsl:otherwise>—</xsl:otherwise>
              </xsl:choose>
            </td>
          </tr>
        </xsl:for-each>
      </tbody>
    </table>
  </xsl:template>

</xsl:stylesheet>
